# User specific aliases and functions

alias .='echo $PWD'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias m='less'
alias e='emacs'
alias v='vim -O'
alias islike='| diff -w -B -s - '
# alias sql='mysql -u root -h 127.0.0.1'
alias ks='ls'
alias ~~='cd ~'
alias gst='git status'
alias gitsum='git st && git diff | cat'
alias csl='ssh tselder@unix4.csc.calpoly.edu'
